{
    "name": "Winners Attendance",
    "version": "17.0.4.0.0",
    "category": "Winners Academy",
    "summary": "Gestion automatique des feuilles de présence Winners Academy",
    "depends": [
        "base",
        "winners_auth",
        "winners_branch",
        "winners_student",
        "winners_group",
        "winners_schedule",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "data/winners_zk_config_data.xml",
        "data/ir_cron_data.xml",
        "views/winners_attendance_anomaly_views.xml",
        "views/winners_attendance_schedule_views.xml",
        "views/winners_attendance_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
